version: "3"
services:
  database:
    image: postgres:15.1-bullseye
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=local
    healthcheck:
      test: pg_isready -U postgres
    volumes:
      - ./database:/var/lib/postgresql/data
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "7156"
    depends_on:
      database:
        condition: service_healthy
  proxy:
    image: nginx:1.23.3-alpine-slim
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Infra/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
