# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build extension

on:
  workflow_dispatch:
    inputs:
      build_version:
        required: true
        description: 'Version of docamatic to build'
      environment:
        required: true
        description: Environment of build to create (ex uat, production)

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: ./setup-env.sh
    - run: npm ci
    - run: ./build.sh ${{ github.event.inputs.build_version }} ${{ github.event.inputs.environment }}
  
    - name: Upload extension artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: extension
        path: ./dist/app.zip
        if-no-files-found: error
        
    - name: Upload homepage artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: homepage
        path: ./dist/homepage
        if-no-files-found: error
        
    - name: Upload sentry artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: sentry
        path: ./dist/sentry
        if-no-files-found: error
