# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: prod-build

on:
  workflow_dispatch:
    inputs:
      prod_build_version:
        required: true
        description: 'Version of docmatic to build and publish'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: ./setup-env.sh
    - run: npm ci
    - run: ./prod-build.sh ${{ github.event.inputs.prod_build_version }}
